import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

interface SummaryPanelProps {
  summary: {
    summary_text: string
    key_points: string[]
    sentiment: 'positive' | 'neutral' | 'negative' | null
  }
}

const sentimentLabel = {
  positive: { label: 'บวก', className: 'bg-green-900/30 text-green-400 border-green-800' },
  neutral: { label: 'กลาง', className: 'bg-gray-900/30 text-gray-400 border-gray-700' },
  negative: { label: 'ลบ', className: 'bg-red-900/30 text-red-400 border-red-800' },
}

export function SummaryPanel({ summary }: SummaryPanelProps) {
  const sentiment = summary.sentiment ? sentimentLabel[summary.sentiment] : null

  return (
    <Card className="border-blue-800/50 bg-blue-950/20">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base">AI Summary</CardTitle>
          {sentiment && (
            <Badge variant="outline" className={sentiment.className}>
              {sentiment.label}
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-sm leading-relaxed">{summary.summary_text}</p>

        {summary.key_points && summary.key_points.length > 0 && (
          <div>
            <p className="text-xs font-medium text-muted-foreground mb-1.5">จุดสำคัญ</p>
            <ul className="space-y-1">
              {(summary.key_points as string[]).map((point, i) => (
                <li key={i} className="text-sm flex gap-2">
                  <span className="text-blue-400 shrink-0">{i + 1}.</span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-xs text-muted-foreground">Generated by Claude Sonnet</p>
      </CardContent>
    </Card>
  )
}
